class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://kcachegrind.github.io/"
  url "https://download.kde.org/stable/applications/16.12.0/src/kcachegrind-16.12.0.tar.xz"
  sha256 "9f73dd8a8cc624a11c54a364fc7583ed16654698df0ac21d25c54fbd4758c018"

  bottle do
    cellar :any
    rebuild 1
    sha256 "4c4e168ec16af7ec028a5b5b5461006066cd67a7733b0b72939da30779db5229" => :sierra
    sha256 "4c4e168ec16af7ec028a5b5b5461006066cd67a7733b0b72939da30779db5229" => :el_capitan
    sha256 "8b2e4ebe8233fe16450ff042742a15e07fc4fae9a534705bfc4d265964207e34" => :yosemite
  end

  depends_on "graphviz" => :optional
  depends_on "qt5"

  def install
    cd "qcachegrind"
    system "#{Formula["qt5"].bin}/qmake", "-spec", "macx-clang", "-config", "release"
    system "make"
    # Install app
    prefix.install "qcachegrind.app"
    # Symlink in the command-line version
    bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
  end
end
